server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
           - id: train-service
             uri: lb://TRAIN-SERVICE
             predicates:
             - Path=/train/**


          global cors:
            cors-configurations:
              '[/**]':
                  allowedOrigins:
                     - "http://localhost:5173"
                  allowedMethods:
                     - "*"
                  allowedHeaders:
                     - "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/